---
title: "Assignment 3:"
subtitle:  "Regional GDP Inequality in 4 Selected European Economies - "
author: "Kristoffer Tufta and Harald Vika"
date: last-modified
date-format: "dddd D MMM, YYYY"
csl: apa7.csl
lang: en-GB
format:
  html: default
  typst:
    papersize: a4
  pdf: 
    documentclass: article
    number-sections: true
    keep-tex: true
    papersize: A4
    fig-pos: "H"
abstract: ""
editor: 
  markdown: 
    wrap: sentence
echo: false
bibliography: references.bib
---

```{r}
#| label: setup
#| include: FALSE
#| message: false
#| warning: false
library (tidyverse)
library (PxWebApiData)
library(readxl)
library(purrr)
library(dineq)
library(psych)
library(flextable)
library(modelsummary)
library(lmtest)

```
 
```{r}
full_dataset <- readRDS("./data/Gini_EUdata_Full.rds")
```

Separating to low, middel and hight segments

```{r}
densitysliced <- cut(full_dataset$Pop_km2, breaks = quantile(full_dataset$Pop_km2, na.rm = TRUE), labels = c("Low density", "Medium density", "High density", "MegaUltradensity"))
table(densitysliced)
```
```{r}
#Population density
Pop_km2_segm <- full_dataset %>%
  select(NUTS2, Geo_Labels, chg_gdpc, gini, Pop_km2) %>% 
  mutate(Segments = cut(Pop_km2,
                           breaks = quantile(Pop_km2, probs = c(0, 1/3, 2/3, 1), na.rm = TRUE),
                           include.lowest = TRUE,
                           labels = c("Low", "Medium", "High")))

```

```{r}
#| label: tbl-MLR
#| fig-cap: "Multiple Regression - Regional GDP Inequality as a function of GDP and population density."
as_flextable (lm(gini ~ chg_gdpc + Pop_km2, data = Pop_km2_segm
))%>%
  colformat_double(j = 2, digits = 6)
``` 
 
 
```{r}
#Workforce
Workforce_segm <- full_dataset %>%
  select(NUTS2, Geo_Labels, chg_gdpc, gini, Workforce) %>% 
  mutate(Segments = cut(Workforce,
                           breaks = quantile(Workforce, probs = c(0, 1/3, 2/3, 1), na.rm = TRUE),
                           include.lowest = TRUE,
                           labels = c("Low", "Medium", "High")))

```

```{r}
#Unemployment rate
Unemp_prct_segm <- full_dataset %>%
  select(NUTS2, Geo_Labels, chg_gdpc, gini, Unemp_prct) %>% 
  mutate(Segments = cut(Unemp_prct,
                           breaks = quantile(Unemp_prct, probs = c(0, 1/3, 2/3, 1), na.rm = TRUE),
                           include.lowest = TRUE,
                           labels = c("Low", "Medium", "High")))
```

